version: '3'

services:
  api:
    container_name: api
    build: ./backend
    ports:
      - "3001:3001"

  database:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"